//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubendo_Remote_Panel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cubendo_Remote_Panel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonEditorSettings_ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick....
        /// </summary>
        internal static string ButtonEditorSettings_ButtonFontNamePick {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_ButtonFontNamePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonEditorSettings_ButtonSave {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Color.
        /// </summary>
        internal static string ButtonEditorSettings_CopyColorMenuItem {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_CopyColorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Button Panel Settings.
        /// </summary>
        internal static string ButtonEditorSettings_FormTitle {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Button Panel Settings.
        /// </summary>
        internal static string ButtonEditorSettings_GroupBoxButtons {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_GroupBoxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsible Control Button Design.
        /// </summary>
        internal static string ButtonEditorSettings_GroupBoxUserCollapse {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_GroupBoxUserCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelBackgroundColour {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Border:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonBorder {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Font:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonFontName {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Font Size:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonFontSize {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Gap:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonGap {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Height:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonHeight {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Width:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelButtonWidth {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelLeftMargin {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelLeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelTopMargin {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelTopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCBackgroundColour {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Border:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonBorder {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Colour:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonColour {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Font:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonFontName {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Font Size:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonFontSize {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Height:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonHeight {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Width:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCButtonWidth {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCLeftMargin {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCLeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin:.
        /// </summary>
        internal static string ButtonEditorSettings_LabelUCTopMargin {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_LabelUCTopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Color.
        /// </summary>
        internal static string ButtonEditorSettings_PasteColorMenuItem {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_PasteColorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick....
        /// </summary>
        internal static string ButtonEditorSettings_UCButtonFontNamePick {
            get {
                return ResourceManager.GetString("ButtonEditorSettings_UCButtonFontNamePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Value.
        /// </summary>
        internal static string ContextMenuCCValue {
            get {
                return ResourceManager.GetString("ContextMenuCCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: {0}.
        /// </summary>
        internal static string ContextMenuChannel {
            get {
                return ResourceManager.GetString("ContextMenuChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Value.
        /// </summary>
        internal static string ContextMenuNoteValue {
            get {
                return ResourceManager.GetString("ContextMenuNoteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Down: {1}.
        /// </summary>
        internal static string ContextMenuValueDown {
            get {
                return ResourceManager.GetString("ContextMenuValueDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Up: {1}.
        /// </summary>
        internal static string ContextMenuValueUp {
            get {
                return ResourceManager.GetString("ContextMenuValueUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one button must remain..
        /// </summary>
        internal static string DialogAtLeastOneButtonMustRemain {
            get {
                return ResourceManager.GetString("DialogAtLeastOneButtonMustRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button file not found..
        /// </summary>
        internal static string DialogButtonFileNotFound {
            get {
                return ResourceManager.GetString("DialogButtonFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancelButton {
            get {
                return ResourceManager.GetString("DialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Button Panel.
        /// </summary>
        internal static string DialogChooseButtonPanel {
            get {
                return ResourceManager.GetString("DialogChooseButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color copied to clipboard..
        /// </summary>
        internal static string DialogColorCopySuccess {
            get {
                return ResourceManager.GetString("DialogColorCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard does not contain a valid color value..
        /// </summary>
        internal static string DialogColorPasteError {
            get {
                return ResourceManager.GetString("DialogColorPasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour:.
        /// </summary>
        internal static string DialogColour {
            get {
                return ResourceManager.GetString("DialogColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this process?.
        /// </summary>
        internal static string DialogConfirmDeleteProcess {
            get {
                return ResourceManager.GetString("DialogConfirmDeleteProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open button file:\n{0}.
        /// </summary>
        internal static string DialogCouldNotOpenButtonFile {
            get {
                return ResourceManager.GetString("DialogCouldNotOpenButtonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Button INI editor:\n{0}.
        /// </summary>
        internal static string DialogCouldNotOpenButtonIniEditor {
            get {
                return ResourceManager.GetString("DialogCouldNotOpenButtonIniEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Global Settings editor:\n{0}.
        /// </summary>
        internal static string DialogCouldNotOpenGlobalSettingsEditor {
            get {
                return ResourceManager.GetString("DialogCouldNotOpenGlobalSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Button Panel.
        /// </summary>
        internal static string DialogCreateNewButtonPanel {
            get {
                return ResourceManager.GetString("DialogCreateNewButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the default buttons.txt!\n\nPlease reinstall the application or restore the missing file..
        /// </summary>
        internal static string DialogDefaultButtonsMissing {
            get {
                return ResourceManager.GetString("DialogDefaultButtonsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Not Allowed.
        /// </summary>
        internal static string DialogDeleteNotAllowed {
            get {
                return ResourceManager.GetString("DialogDeleteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Panel Name:.
        /// </summary>
        internal static string DialogEnterNewPanelName {
            get {
                return ResourceManager.GetString("DialogEnterNewPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send key sequence:\n{0}.
        /// </summary>
        internal static string DialogFailedToSendKeySequence {
            get {
                return ResourceManager.GetString("DialogFailedToSendKeySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel files already exist:\n{0}\n{1}\nOverwrite?.
        /// </summary>
        internal static string DialogFileExists {
            get {
                return ResourceManager.GetString("DialogFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini file not found..
        /// </summary>
        internal static string DialogIniFileNotFound {
            get {
                return ResourceManager.GetString("DialogIniFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel file name is invalid or missing..
        /// </summary>
        internal static string DialogInvalidPanelFile {
            get {
                return ResourceManager.GetString("DialogInvalidPanelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name cannot be empty..
        /// </summary>
        internal static string DialogInvalidProcessName {
            get {
                return ResourceManager.GetString("DialogInvalidProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default MIDI port from your ini file was not found.\n\nContinue without MIDI functionality?\n\nYou will need to restart the app to use MIDI functionality..
        /// </summary>
        internal static string DialogLoopMidiNotRunning {
            get {
                return ResourceManager.GetString("DialogLoopMidiNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Device Not Found.
        /// </summary>
        internal static string DialogMidiDeviceNotFound {
            get {
                return ResourceManager.GetString("DialogMidiDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my panel.
        /// </summary>
        internal static string DialogMyPanel {
            get {
                return ResourceManager.GetString("DialogMyPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DialogName {
            get {
                return ResourceManager.GetString("DialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No button panel files found..
        /// </summary>
        internal static string DialogNoButtonPanelFilesFound {
            get {
                return ResourceManager.GetString("DialogNoButtonPanelFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New button panel created:\n{0}.
        /// </summary>
        internal static string DialogPanelCreated {
            get {
                return ResourceManager.GetString("DialogPanelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel File Missing.
        /// </summary>
        internal static string DialogPanelFileMissing {
            get {
                return ResourceManager.GetString("DialogPanelFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF manual not found!.
        /// </summary>
        internal static string DialogPdfManualNotFound {
            get {
                return ResourceManager.GetString("DialogPdfManualNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid color name (e.g. Red) or hex code (e.g. #ff0000)..
        /// </summary>
        internal static string DialogPleaseEnterValidColor {
            get {
                return ResourceManager.GetString("DialogPleaseEnterValidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New process added..
        /// </summary>
        internal static string DialogProcessAdded {
            get {
                return ResourceManager.GetString("DialogProcessAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process deleted..
        /// </summary>
        internal static string DialogProcessDeleted {
            get {
                return ResourceManager.GetString("DialogProcessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to README.txt not found..
        /// </summary>
        internal static string DialogReadmeNotFound {
            get {
                return ResourceManager.GetString("DialogReadmeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Header ID#{0}.
        /// </summary>
        internal static string DialogSectionHeaderId {
            get {
                return ResourceManager.GetString("DialogSectionHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section name cannot be empty..
        /// </summary>
        internal static string DialogSectionNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DialogSectionNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Button Panel:.
        /// </summary>
        internal static string DialogSelectButtonPanel {
            get {
                return ResourceManager.GetString("DialogSelectButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send key sequence:\n{0}.
        /// </summary>
        internal static string DialogSendKeyFailed {
            get {
                return ResourceManager.GetString("DialogSendKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.ini file not found..
        /// </summary>
        internal static string DialogSettingsIniFileNotFound {
            get {
                return ResourceManager.GetString("DialogSettingsIniFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings. Some values may not be available..
        /// </summary>
        internal static string DialogSettingsLoadError {
            get {
                return ResourceManager.GetString("DialogSettingsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully..
        /// </summary>
        internal static string DialogSettingsSaved {
            get {
                return ResourceManager.GetString("DialogSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings. Please check file permissions..
        /// </summary>
        internal static string DialogSettingsSaveError {
            get {
                return ResourceManager.GetString("DialogSettingsSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string DialogValidation {
            get {
                return ResourceManager.GetString("DialogValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Transparency.
        /// </summary>
        internal static string DialogWindowTransparency {
            get {
                return ResourceManager.GetString("DialogWindowTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string EditMidiActionForm_Add {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditMidiActionForm_Cancel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel:.
        /// </summary>
        internal static string EditMidiActionForm_Channel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new button:
        ///Name: {0}
        ///Tooltip: {1}
        ///Channel: {2}
        ///Type: {3}
        ///{4}
        ///Down Value: {5}
        ///Up Value: {6}
        ///
        ///Proceed?.
        /// </summary>
        internal static string EditMidiActionForm_ConfirmAddText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ConfirmAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Add.
        /// </summary>
        internal static string EditMidiActionForm_ConfirmAddTitle {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ConfirmAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this button.
        ///Are you sure?.
        /// </summary>
        internal static string EditMidiActionForm_ConfirmDeleteText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string EditMidiActionForm_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string EditMidiActionForm_Delete {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string EditMidiActionForm_MouseUpX {
            get {
                return ResourceManager.GetString("EditMidiActionForm_MouseUpX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        internal static string EditMidiActionForm_MoveLeft {
            get {
                return ResourceManager.GetString("EditMidiActionForm_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        internal static string EditMidiActionForm_MoveRight {
            get {
                return ResourceManager.GetString("EditMidiActionForm_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string EditMidiActionForm_Name {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press:.
        /// </summary>
        internal static string EditMidiActionForm_Press {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release:.
        /// </summary>
        internal static string EditMidiActionForm_Release {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditMidiActionForm_Save {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Saved.
        /// </summary>
        internal static string EditMidiActionForm_SaveMsgText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_SaveMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditMidiActionForm_SaveMsgTitle {
            get {
                return ResourceManager.GetString("EditMidiActionForm_SaveMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Button Action.
        /// </summary>
        internal static string EditMidiActionForm_Title {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip:.
        /// </summary>
        internal static string EditMidiActionForm_Tooltip {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new button with these settings.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_AddButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and close this dialog.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_CancelButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI channel (1-16).
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ChannelLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI channel (1-16).
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ChannelNumeric {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ChannelNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this button.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_DeleteButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Command
        ///Use &quot;+&quot; to add multiple keys
        ///Double click to use editor.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_KeyStringTextBox {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_KeyStringTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the button release value.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_MouseUpXLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_MouseUpXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this button to the left.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_MoveLeftButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_MoveLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this button to the right.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_MoveRightButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_MoveRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button name (displayed on panel).
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_NameLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the button&apos;s display name.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_NameTextBox {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_NameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is pressed.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_PressLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_PressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is pressed.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_PressNumeric {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_PressNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is pressed.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_PressNumericText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_PressNumericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is released.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ReleaseLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ReleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is released.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ReleaseNumeric {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ReleaseNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value sent when button is released.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ReleaseNumericText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ReleaseNumericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to this button.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_SaveButton {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip text (shown on hover).
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_TooltipLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_TooltipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip for this button
        ///To make a new line use
        ///backslash + lower case n.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_TooltipTextBox {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_TooltipTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC, Note or Key.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_TypeComboBox {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_TypeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC, Note or Key.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_TypeLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Value
        ///Note Number
        ///Key Command.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ValueLabel {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Value
        ///Note Number.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ValueNumeric {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ValueNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC or Note Value, or Hot Keys.
        /// </summary>
        internal static string EditMidiActionForm_ToolTip_ValueNumericText {
            get {
                return ResourceManager.GetString("EditMidiActionForm_ToolTip_ValueNumericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string EditMidiActionForm_Type {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string EditMidiActionForm_Value {
            get {
                return ResourceManager.GetString("EditMidiActionForm_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN Remote {0} : {1}.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string GlobalEditorSettings_ButtonAddProcess {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_ButtonAddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GlobalEditorSettings_ButtonCancel {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string GlobalEditorSettings_ButtonDeleteProcess {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_ButtonDeleteProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GlobalEditorSettings_ButtonOK {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Global Settings.
        /// </summary>
        internal static string GlobalEditorSettings_FormTitle {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Switch (Expert!).
        /// </summary>
        internal static string GlobalEditorSettings_GroupBoxAutoSwitch {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_GroupBoxAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Activity Buttons.
        /// </summary>
        internal static string GlobalEditorSettings_GroupBoxMidiActivity {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_GroupBoxMidiActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default MIDI Ports.
        /// </summary>
        internal static string GlobalEditorSettings_GroupBoxMidiPorts {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_GroupBoxMidiPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string GlobalEditorSettings_GroupBoxProcesses {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_GroupBoxProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Settings.
        /// </summary>
        internal static string GlobalEditorSettings_GroupBoxTooltips {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_GroupBoxTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Switch Debounce:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelAutoSwitchDebounce {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelAutoSwitchDebounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Switch Check:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelAutoSwitchInterval {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelAutoSwitchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Press Glow Colour:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelButtonGlowDown {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelButtonGlowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Release Glow Colour:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelButtonGlowUp {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelButtonGlowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Panel:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelFallbackPanel {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelFallbackPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelLanguage {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI In Activity Colour:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelMidiInColour {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelMidiInColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Panel:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelPanel {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel MIDI In:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelPanelMidiIn {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelPanelMidiIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel MIDI Out:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelPanelMidiOut {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelPanelMidiOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process MIDI In:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelProcessMidiIn {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelProcessMidiIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process MIDI Out:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelProcessMidiOut {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelProcessMidiOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelProcessName {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Background:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelTooltipBack {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelTooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Text:.
        /// </summary>
        internal static string GlobalEditorSettings_LabelTooltipText {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LabelTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New language will be used after restarting the application.
        /// </summary>
        internal static string GlobalEditorSettings_LanguageChangedMessage {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LanguageChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        internal static string GlobalEditorSettings_LanguageChangedTitle {
            get {
                return ResourceManager.GetString("GlobalEditorSettings_LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Key String.
        /// </summary>
        internal static string KeyStringEntryForm_Title {
            get {
                return ResourceManager.GetString("KeyStringEntryForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CRP Version {0}.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        internal static string MenuAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Switch.
        /// </summary>
        internal static string MenuAutoSwitch {
            get {
                return ResourceManager.GetString("MenuAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Colour.
        /// </summary>
        internal static string MenuCopyColour {
            get {
                return ResourceManager.GetString("MenuCopyColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Button Panel.
        /// </summary>
        internal static string MenuCreateNewButtonPanel {
            get {
                return ResourceManager.GetString("MenuCreateNewButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Section Headers.
        /// </summary>
        internal static string MenuDisplaySectionHeaders {
            get {
                return ResourceManager.GetString("MenuDisplaySectionHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Button File.
        /// </summary>
        internal static string MenuEditButtonFile {
            get {
                return ResourceManager.GetString("MenuEditButtonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Global Settings.
        /// </summary>
        internal static string MenuEditGlobalSettings {
            get {
                return ResourceManager.GetString("MenuEditGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Panel Settings.
        /// </summary>
        internal static string MenuEditPanelSettings {
            get {
                return ResourceManager.GetString("MenuEditPanelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Collapsible.
        /// </summary>
        internal static string MenuMakeCollapsible {
            get {
                return ResourceManager.GetString("MenuMakeCollapsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Collapsible!.
        /// </summary>
        internal static string MenuMakeCollapsibleHidesTitleBar {
            get {
                return ResourceManager.GetString("MenuMakeCollapsibleHidesTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Panel to Centre.
        /// </summary>
        internal static string MenuMovePanelToCentre {
            get {
                return ResourceManager.GetString("MenuMovePanelToCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Transparency.
        /// </summary>
        internal static string MenuPanelTransparency {
            get {
                return ResourceManager.GetString("MenuPanelTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Colour.
        /// </summary>
        internal static string MenuPasteColour {
            get {
                return ResourceManager.GetString("MenuPasteColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Current Panel.
        /// </summary>
        internal static string MenuRefreshCurrentPanel {
            get {
                return ResourceManager.GetString("MenuRefreshCurrentPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Button Panel.
        /// </summary>
        internal static string MenuSelectButtonPanel {
            get {
                return ResourceManager.GetString("MenuSelectButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MIDI In From Host.
        /// </summary>
        internal static string MenuShowMidiInFromHost {
            get {
                return ResourceManager.GetString("MenuShowMidiInFromHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status.
        /// </summary>
        internal static string MenuShowStatus {
            get {
                return ResourceManager.GetString("MenuShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Title Bar.
        /// </summary>
        internal static string MenuShowTitleBar {
            get {
                return ResourceManager.GetString("MenuShowTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View PDF Manual.
        /// </summary>
        internal static string MenuViewPdfManual {
            get {
                return ResourceManager.GetString("MenuViewPdfManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View README.
        /// </summary>
        internal static string MenuViewReadme {
            get {
                return ResourceManager.GetString("MenuViewReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active DAW: {0}.
        /// </summary>
        internal static string StatusActiveDaw {
            get {
                return ResourceManager.GetString("StatusActiveDaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOT: {0}.
        /// </summary>
        internal static string StatusAOT {
            get {
                return ResourceManager.GetString("StatusAOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI In: {0}.
        /// </summary>
        internal static string StatusMidiIn {
            get {
                return ResourceManager.GetString("StatusMidiIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Out: {0}.
        /// </summary>
        internal static string StatusMidiOut {
            get {
                return ResourceManager.GetString("StatusMidiOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string TrayExitApplication {
            get {
                return ResourceManager.GetString("TrayExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / Hide.
        /// </summary>
        internal static string TrayShowHide {
            get {
                return ResourceManager.GetString("TrayShowHide", resourceCulture);
            }
        }
    }
}
